name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  base-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build base images
        run: sh build-base-images.sh bspaulding/devcontainer-

  push:
    needs: base-images

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        include:
          - image-name: 'alpine'
            base: 'alpine'
            tag: 'latest'
          - image-name: 'ubuntu'
            base: 'ubuntu'
            tag: 'latest'
          - image-name: 'clojure'
            base: 'clojure'
            tag: 'openjdk-17-tools-deps-alpine'
          - image-name: 'haskell'
            base: 'haskell'
            tag: 'latest'
          - image-name: 'node'
            base: 'node'
            tag: '15-alpine'
          - image-name: 'python'
            base: 'python'
            tag: '3-alpine'
          - image-name: 'rust'
            base: 'rust'
            tag: 'alpine'
          - image-name: 'go'
            base: 'golang'
            tag: 'alpine'
          - image-name: 'ruby'
            base: 'ruby'
            tag: '3.0.3'
            
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_NAME=devcontainer-${{ matrix.image-name }}
          echo IMAGE_NAME=$IMAGE_NAME
          IMAGE_TAG=${{ matrix.tag }}
          echo IMAGE_TAG=$IMAGE_TAG

          IMAGE_ID=bspaulding/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker build . --file Dockerfile --build-arg base=${{ matrix.base }}:${{ matrix.tag }} --tag $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG
